//LOAD
export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_REQUESTS = 'LOAD_REQUESTS';
export const LOAD_REQUESTS_TYPE = 'LOAD_REQUESTS_TYPE';
export const LOAD_NEXT_INBOX = 'LOAD_NEXT_INBOX';
export const LOAD_NEXT_OUTBOX = 'LOAD_NEXT_OUTBOX';

//CHANGE
export const CHANGE_VISIBILITY_FILTERS = 'CHANGE_VISIBILITY_FILTERS';
export const CHOICE_PERIOD_FILTERS = 'CHOICE_PERIOD_FILTERS';
export const SET_VISIBILITY_FILTERS = 'SET_VISIBILITY_FILTERS';
export const TOGGLE_IMPORTANT_FILTERS = 'TOGGLE_IMPORTANT_FILTERS';
export const SET_DATE_RANGE_FILTERS = 'SET_DATE_RANGE_FILTERS';
export const RESET_FILTERS = 'RESET_FILTERS';

export const TOGGLE_INBOX_REQUEST_IMPORTANT_FLAG = 'TOGGLE_INBOX_REQUEST_IMPORTANT_FLAG';
export const TOGGLE_OUTBOX_REQUEST_IMPORTANT_FLAG = 'TOGGLE_OUTBOX_REQUEST_IMPORTANT_FLAG';

//FILTER_TYPES
export const VisibilityFilters = {
    PERIOD_FILTER: 'PERIOD_FILTER',
    USER_FILTER: 'USER_FILTER',
    TYPE_FILTER: 'TYPE_FILTER',
    DATEPICKER: 'DATEPICKER'
};